#!/bin/bash

set -e

# Install sqlx-cli if needed
[[ "$(sqlx --version)" == "sqlx-cli 0.6.2" ]] || cargo install sqlx-cli --version 0.6.2

cd crates/db

mkdir -p /tmp/zed-client-db
DATABASE_URL=sqlite:///tmp/zed-client-db/test.db

cargo sqlx -D $DATABASE_URL database drop
cargo sqlx -D $DATABASE_URL database setup
cargo sqlx prepare -- --offline