// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Size { minWidth: number | null, maxWidth: number | null, maximizeWidth: boolean, minHeight: number | null, maxHeight: number | null, maximizeHeight: boolean, }